/* Swim meet checker — all logic runs in the browser. No server, no tokens.
 * Data comes from swim-data.js (window.SWIM_DATA / SWIM_STANDARDS), regenerated by
 * code/swim_data.py. Meet PDFs are parsed client-side with pdf.js. The pure functions
 * below are also require()-able in Node for testing (see code/test_webapp.js). */
(function (root) {
  "use strict";

  var STROKE = {Freestyle: "Free", Backstroke: "Back", Breaststroke: "Breast",
                Butterfly: "Fly", "Individual Medley": "IM", Medley: "IM",
                Free: "Free", Back: "Back", Breast: "Breast", Fly: "Fly", IM: "IM"};
  var GROUP_ELIGIBLE = {
    "10&U": ["10 & Under"], "11-12": ["11-12"], "13-14": ["13-14"],
    "12&U": ["10 & Under", "11-12"], "11&Over": ["11-12", "13-14"], "13&Over": ["13-14"]};
  var ORDER = ["B", "BB", "A", "AA", "AAA", "AAAA"];
  var GOOD = 2.0, STRETCH = 4.0, STALE_DAYS = 120;
  var TIME_RE = /#?\d{1,2}:\d{2}\.\d{2}|#?\d{1,3}\.\d{2}/g;
  var EVENT_RE = /(\d{1,2}\s*&\s*U(?:nder)?|\d{1,2}\s*&\s*Over|11-12|13-14)\s+(\d{2,4})\s+(?:[MYmy]\s+)?(Freestyle|Backstroke|Breaststroke|Butterfly|Individual Medley|Medley|Free|Back|Breast|Fly|IM)\b/;
  function normGroup(g) { return g.replace(/\s+/g, "").replace("Under", "U"); }
  var MONTHS = ["January","February","March","April","May","June","July","August",
                "September","October","November","December"];

  function cs(tok) {
    tok = String(tok).replace(/^#/, "");
    if (tok.indexOf(":") >= 0) {
      var p = tok.split(":");
      return parseInt(p[0], 10) * 6000 + Math.round(parseFloat(p[1]) * 100);
    }
    return Math.round(parseFloat(tok) * 100);
  }
  function csToStr(c) {
    var neg = c < 0; c = Math.abs(c);
    var m = Math.floor(c / 6000), s = (c % 6000) / 100;
    var ss = s.toFixed(2);
    return (neg ? "-" : "") + (m ? m + ":" + (s < 10 ? "0" : "") + ss : ss);
  }
  function daysSince(iso) {
    if (!iso) return null;
    var d = new Date(iso + "T00:00:00"), now = new Date();
    if (isNaN(d)) return null;
    return Math.floor((now - d) / 86400000);
  }
  function within(iso, start) {
    if (!start) return true;
    return new Date(iso) >= new Date(start);
  }

  // ---- meet-PDF parsing (mirrors code/meet_pdf.py) ----
  function parseGroups(text) {
    var groups = {}, timed = 0, lines = text.split("\n");
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      var m = EVENT_RE.exec(line);
      if (!m || line.indexOf("Relay") >= 0) continue;
      var grp = normGroup(m[1]);
      var event = parseInt(m[2], 10) + " " + STROKE[m[3]];
      var before = line.slice(0, m.index), after = line.slice(m.index + m[0].length);
      var ta = after.match(TIME_RE) || [];
      var num = eventNum(before, after);
      var g = groups[grp] || (groups[grp] = {});
      if (ta.length >= 2) { g[event] = {cutLCM: cs(ta[0]), cutSCY: cs(ta[1]), num: num}; timed++; }
      else if (!g[event]) g[event] = {num: num};
      else if (num && g[event].num == null) g[event].num = num;
    }
    return {groups: groups, cutType: timed >= 4 ? "qualify" : "none"};
  }
  // Men's event number: trailing int after the men's times, else leading int (open list).
  function eventNum(before, after) {
    var a = after.replace(TIME_RE, " ").match(/\d{1,3}/g);
    if (a) return parseInt(a[a.length - 1], 10);
    var b = before.replace(TIME_RE, " ").match(/\d{1,3}/g);
    return b ? parseInt(b[0], 10) : null;
  }

  function meetMeta(text) {
    var head = text.split("\n").slice(0, 15).map(function (l) {
      return l.trim().replace(/\s{2,}.*$/, "");
    });
    var idx = -1;
    for (var i = 0; i < head.length; i++)
      if (/Championship|Invitational|Classic|Champs|\bOpen\b/.test(head[i]) && head[i].length > 8) { idx = i; break; }
    var name = "";
    if (idx >= 0) {
      var parts = [];
      [idx - 2, idx - 1, idx].forEach(function (j) {
        if (j >= 0 && head[j] && (j === idx || /PVS|\d{4}|Course/.test(head[j])))
          if (parts.indexOf(head[j]) < 0) parts.push(head[j]);
      });
      name = parts.join(" ");
    }
    var course = /Long Course|LCM/.test(text) ? "LCM" : (/Short Course Yards|SCY/.test(text) ? "SCY" : "LCM");
    var d = text.match(/(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2})[\d,&\s-]*?(\d{4})/);
    var start = d ? d[3] + "-" + pad(MONTHS.indexOf(d[1]) + 1) + "-" + pad(d[2]) : "";
    var w = text.match(/prior to\s+(\w+)\s+(\d{1,2}),?\s+(\d{4})/);
    var win = w ? w[3] + "-" + pad(MONTHS.indexOf(w[1]) + 1) + "-" + pad(w[2]) : "";
    var nums = {one:1, two:2, three:3, four:4, five:5, six:6, seven:7, eight:8};
    var mx = text.match(/(?:maximum of|enter up to)\s+(\w+)(?:\s*\((\d+)\))?\s+(?:individual\s+)?events/);
    var maxEv = null;
    if (mx) maxEv = mx[2] ? parseInt(mx[2], 10)
      : (/^\d+$/.test(mx[1]) ? parseInt(mx[1], 10) : (nums[mx[1].toLowerCase()] || null));
    var b = text.match(/(?:up to\s+)?(?:a total of\s+)?(\w+)\s*\((\d+)\)\s+bonus events/i);
    var bonus = b ? parseInt(b[2], 10) : 0;
    return {name: name, course: course, start: start, window: win, maxEvents: maxEv, bonus: bonus};
  }
  function pad(n) { return (n < 10 ? "0" : "") + n; }

  function toSpec(text) {
    var pg = parseGroups(text), meta = meetMeta(text), events = {};
    Object.keys(pg.groups).forEach(function (pdfGrp) {
      (GROUP_ELIGIBLE[pdfGrp] || []).forEach(function (swimGrp) {
        var dest = events[swimGrp] || (events[swimGrp] = {});
        Object.keys(pg.groups[pdfGrp]).forEach(function (ev) {
          var cut = pg.groups[pdfGrp][ev];
          if (!(ev in dest) || (Object.keys(cut).length && !Object.keys(dest[ev]).length))
            dest[ev] = Object.assign({}, cut);
        });
      });
    });
    return {meet: meta.name || "Meet", course: meta.course, startDate: meta.start,
            maxIndividualEvents: meta.maxEvents, cutType: pg.cutType,
            qualifyingWindowStart: meta.window, bonusEvents: meta.bonus, events: events};
  }

  // ---- per-swimmer PB lookup ----
  function pbsByEvent(sw) {
    var pbs = {};
    (sw.usasBest || []).forEach(function (r) {
      (pbs[r.event] || (pbs[r.event] = {}))[r.course] = r;
    });
    (sw.nvslBest || []).forEach(function (r) {
      var c = Object.assign({}, r, {course: "NVSL"});
      (pbs[r.event] || (pbs[r.event] = {})).NVSL = c;
    });
    return pbs;
  }

  function gapToNext(stdRow, level, c) {
    if (!stdRow) return [null, null];
    var tgt;
    if (ORDER.indexOf(level) < 0) tgt = "B";
    else if (ORDER.indexOf(level) === ORDER.length - 1) return [null, null];
    else tgt = ORDER[ORDER.indexOf(level) + 1];
    if (!(tgt in stdRow)) return [null, null];
    return [tgt, c - stdRow[tgt]];
  }

  // ---- analysis (mirrors code/meet_check.py) ----
  function analyze(spec, data, standards) {
    return spec.cutType === "qualify"
      ? analyzeQualify(spec, data)
      : analyzeOpen(spec, data, standards);
  }

  function analyzeQualify(spec, data) {
    var out = {type: "qualify", meet: spec.meet, course: spec.course,
               startDate: spec.startDate, window: spec.qualifyingWindowStart, swimmers: []};
    data.swimmers.forEach(function (sw) {
      var offered = spec.events[sw.ageGroup] || {}, pbs = pbsByEvent(sw);
      var qual = [], near = [], notime = [];
      Object.keys(offered).forEach(function (ev) {
        var cut = offered[ev], lcm = (pbs[ev] || {}).LCM, scy = (pbs[ev] || {}).SCY;
        var hits = [];
        if (lcm && cut.cutLCM && lcm.cs <= cut.cutLCM && within(lcm.date, spec.qualifyingWindowStart))
          hits.push(["LCM", cut.cutLCM - lcm.cs, lcm, cut.cutLCM]);
        if (scy && cut.cutSCY && scy.cs <= cut.cutSCY && within(scy.date, spec.qualifyingWindowStart))
          hits.push(["SCY", cut.cutSCY - scy.cs, scy, cut.cutSCY]);
        if (hits.length) {
          hits.sort(function (a, b) { return b[1] - a[1]; });
          qual.push({event: ev, num: cut.num, course: hits[0][0], under: hits[0][1], row: hits[0][2], std: hits[0][3]});
        } else if (lcm || scy) {
          var gaps = [];
          if (lcm && cut.cutLCM) gaps.push(["LCM", lcm.cs - cut.cutLCM, lcm, cut.cutLCM]);
          if (scy && cut.cutSCY) gaps.push(["SCY", scy.cs - cut.cutSCY, scy, cut.cutSCY]);
          if (gaps.length) {
            gaps.sort(function (a, b) { return a[1] - b[1]; });
            near.push({event: ev, num: cut.num, course: gaps[0][0], off: gaps[0][1], row: gaps[0][2], std: gaps[0][3]});
          }
        } else notime.push(ev);
      });
      qual.sort(function (a, b) { return b.under - a.under; });
      near.sort(function (a, b) { return a.off - b.off; });
      var cap = spec.maxIndividualEvents || (qual.length + near.length + notime.length);
      var bonusAllow = spec.bonusEvents || 0;
      var DISTANCE = {"400 IM": 1, "400 Free": 1, "800 Free": 1, "1500 Free": 1};
      var enter = qual.slice(0, cap).map(function (q) { return q.event; });
      var bonus = [];
      if (bonusAllow && qual.length && enter.length < cap) {
        var room = Math.min(bonusAllow, cap - enter.length);
        var cands = near.filter(function (n) { return !DISTANCE[n.event]; })
          .map(function (n) { return n.event; })
          .concat(notime.filter(function (e) { return !DISTANCE[e]; }));
        bonus = cands.slice(0, room);
      }
      var numOf = {};
      Object.keys(offered).forEach(function (e) { numOf[e] = (offered[e] || {}).num; });
      out.swimmers.push({name: sw.name, age: sw.age, ageGroup: sw.ageGroup,
                         hasEvents: !!Object.keys(offered).length, numOf: numOf,
                         qual: qual, near: near.slice(0, 6), notime: notime,
                         enter: enter, bonus: bonus, bonusAllow: bonusAllow,
                         cap: cap, chase: near.slice(0, 2)});
    });
    return out;
  }

  function analyzeOpen(spec, data, standards) {
    var course = spec.course, maxEv = spec.maxIndividualEvents || 3;
    var out = {type: "open", meet: spec.meet, course: course,
               startDate: spec.startDate, maxEvents: maxEv, swimmers: []};
    data.swimmers.forEach(function (sw) {
      var grp = sw.ageGroup, offered = spec.events[grp] || {}, pbs = pbsByEvent(sw);
      var rows = [];
      Object.keys(offered).forEach(function (ev) {
        var here = (pbs[ev] || {})[course], other = null;
        if (!here) {
          var vals = Object.keys(pbs[ev] || {}).map(function (c) { return pbs[ev][c]; });
          vals.sort(function (a, b) { return a.cs - b.cs; });
          other = vals[0] || null;
        }
        var level = here ? (here.standard || "<B") : "NT";
        if (/^slower/i.test(level)) level = "<B";
        var nxt = null, need = null;
        if (here) {
          var lvl = ORDER.indexOf(level) >= 0 ? level : "<B";
          var gn = gapToNext(standards[grp + "|" + course + "|" + ev], lvl, here.cs);
          nxt = gn[0]; need = gn[1];
          if (need !== null && need <= 0) need = null;
        }
        var pct = need ? 100 * need / here.cs : null;
        var days = here ? daysSince(here.date) : null;
        rows.push({event: ev, num: (offered[ev] || {}).num, here: here, other: other,
                   level: level, next: nxt || "", need: need, pct: pct, days: days,
                   stale: days !== null && days >= STALE_DAYS});
      });
      rows.sort(function (a, b) {
        return (a.pct === null) - (b.pct === null) || (a.pct || 999) - (b.pct || 999);
      });
      var timed = rows.filter(function (r) { return r.pct !== null; });
      var picks = timed.slice().sort(function (a, b) { return a.pct - b.pct; }).slice(0, maxEv);
      var stalePool = timed.filter(function (r) { return r.stale && picks.indexOf(r) < 0; })
                           .sort(function (a, b) { return b.days - a.days; });
      var explore = stalePool[0] || null;
      var droppable = picks.filter(function (r) { return !r.stale && r.pct > GOOD; });
      if (explore && droppable.length) {
        var worst = droppable.reduce(function (a, b) { return a.pct >= b.pct ? a : b; });
        picks = picks.filter(function (r) { return r !== worst; }).concat([explore]);
      } else if (explore && picks.length < maxEv) picks = picks.concat([explore]);
      picks.sort(function (a, b) { return a.pct - b.pct; });
      out.swimmers.push({name: sw.name, age: sw.age, ageGroup: grp,
                         hasEvents: !!Object.keys(offered).length, rows: rows,
                         picks: picks, explore: explore,
                         blind: rows.filter(function (r) { return !r.here; })});
    });
    return out;
  }

  var api = {cs: cs, csToStr: csToStr, daysSince: daysSince, parseGroups: parseGroups,
             meetMeta: meetMeta, toSpec: toSpec, analyze: analyze,
             GOOD: GOOD, STRETCH: STRETCH};
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.SwimLogic = api;
})(typeof self !== "undefined" ? self : this);
